# Project
group=net.coolsimulations.ForgottenEngineers

# Common
minecraft_version=26.3

# Forge
forge_version=66.0.3

# Fabric
fabric_version=0.161.0
fabric_loader_version=0.19.5

# NeoForge
neoforge_version=26.3.0.16-beta

# Mod options
mod_version=1.2.0
mod_name=Forgotten Engineers
mod_author=coolsim
mod_id=forgottenengineers
mod_desc=Rediscover forgotten engineering to automate your inventory and extend your adventures
mod_credit=ModJam 2026 'Echos of the Past'
mod_homepage=https://curseforge.com/minecraft/mc-mods/forgotten-engineers
mod_source=https://github.com/coolsimulations/Forgotten-Engineers
mod_issues=https://github.com/coolsimulations/Forgotten-Engineers/issues
mod_update_url=https://coolsimulations.net/mcmods/forgottenengineers-versionchecker.json
mod_license=All rights reserved

# Dependency options
modmenu_version=21.0.0
cloth_version=26.3.158
opencc4j=1.14.0

# Gradle
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn

# Forge configuration
net.minecraftforge.gradle.merge-source-sets=true